import 'dotenv/config';
import mongoose from 'mongoose';
import Sale from '../models/Sale.js';

const newData = [
  {customerId:'CUST-49004',customerName:'Nisha Iyer',phoneNumber:'9931820859',gender:'Male',age:52,customerRegion:'South',customerType:'Returning',productId:'PROD-2579',productName:'Formal Shirt',brand:'UrbanWeave',productCategory:'Clothing',tags:['unisex','casual','formal','fashion'],quantity:5,pricePerUnit:2528,discountPercentage:11,totalAmount:12640,finalAmount:11249.6,date:new Date('2021-11-23'),paymentMethod:'Cash',orderStatus:'Cancelled',deliveryType:'Express',storeId:'ST-021',storeLocation:'Jaipur',salespersonId:'EMP-7051',employeeName:'Kulasekhar Busi'},
  {customerId:'CUST-92264',customerName:'Aisha Iyer',phoneNumber:'9724653947',gender:'Female',age:31,customerRegion:'Central',customerType:'New',productId:'PROD-1775',productName:'Gaming Mouse',brand:'NovaGear',productCategory:'Electronics',tags:['gadgets','accessories','smart','wireless'],quantity:2,pricePerUnit:248,discountPercentage:24,totalAmount:496,finalAmount:376.96,date:new Date('2022-03-26'),paymentMethod:'UPI',orderStatus:'Pending',deliveryType:'Store Pickup',storeId:'ST-019',storeLocation:'Pune',salespersonId:'EMP-4284',employeeName:'Khushi Agarwal'},
  {customerId:'CUST-71546',customerName:'Anjali Agarwal',phoneNumber:'9575934556',gender:'Female',age:57,customerRegion:'South',customerType:'Loyal',productId:'PROD-7195',productName:'Gaming Mouse',brand:'NovaGear',productCategory:'Electronics',tags:['accessories','gadgets','smart','wireless'],quantity:2,pricePerUnit:1679,discountPercentage:14,totalAmount:3358,finalAmount:2887.88,date:new Date('2022-06-17'),paymentMethod:'UPI',orderStatus:'Cancelled',deliveryType:'Standard',storeId:'ST-010',storeLocation:'Jaipur',salespersonId:'EMP-5276',employeeName:'Kulasekhar Busi'},
  {customerId:'CUST-56241',customerName:'Vivek Chopra',phoneNumber:'9022368293',gender:'Male',age:56,customerRegion:'North',customerType:'Loyal',productId:'PROD-7136',productName:'Skin Repair Serum',brand:'VelvetTouch',productCategory:'Beauty',tags:['skincare','makeup'],quantity:2,pricePerUnit:3431,discountPercentage:14,totalAmount:6862,finalAmount:5901.32,date:new Date('2023-06-10'),paymentMethod:'Net Banking',orderStatus:'Returned',deliveryType:'Express',storeId:'ST-010',storeLocation:'Mumbai',salespersonId:'EMP-5101',employeeName:'Harsh Agarwal'},
  {customerId:'CUST-80966',customerName:'Alisha Yadav',phoneNumber:'9364835973',gender:'Male',age:31,customerRegion:'North',customerType:'New',productId:'PROD-9309',productName:'Cotton T-Shirt',brand:'StreetLayer',productCategory:'Clothing',tags:['formal','casual','unisex'],quantity:4,pricePerUnit:3248,discountPercentage:31,totalAmount:12992,finalAmount:8964.48,date:new Date('2021-03-04'),paymentMethod:'Wallet',orderStatus:'Cancelled',deliveryType:'Store Pickup',storeId:'ST-035',storeLocation:'Mumbai',salespersonId:'EMP-9813',employeeName:'Ankit Tiwari'},
  {customerId:'CUST-66475',customerName:'Kabir Das',phoneNumber:'9405971426',gender:'Female',age:21,customerRegion:'Central',customerType:'Loyal',productId:'PROD-6315',productName:'Aloe Vera Gel',brand:'PureBloom',productCategory:'Beauty',tags:['makeup','skincare','beauty','organic'],quantity:4,pricePerUnit:3056,discountPercentage:5,totalAmount:12224,finalAmount:11612.8,date:new Date('2022-01-07'),paymentMethod:'Credit Card',orderStatus:'Pending',deliveryType:'Standard',storeId:'ST-021',storeLocation:'Kolkata',salespersonId:'EMP-8523',employeeName:'Deepak Goyal'},
  {customerId:'CUST-67622',customerName:'Simran Singh',phoneNumber:'9114499377',gender:'Female',age:43,customerRegion:'Central',customerType:'New',productId:'PROD-8043',productName:'Smartwatch',brand:'NovaGear',productCategory:'Electronics',tags:['wireless','smart','accessories'],quantity:1,pricePerUnit:2216,discountPercentage:16,totalAmount:2216,finalAmount:1861.44,date:new Date('2022-03-15'),paymentMethod:'UPI',orderStatus:'Returned',deliveryType:'Express',storeId:'ST-002',storeLocation:'Lucknow',salespersonId:'EMP-9353',employeeName:'Ram Chaudhry'},
  {customerId:'CUST-69388',customerName:'Anjali Patel',phoneNumber:'9838500096',gender:'Male',age:55,customerRegion:'East',customerType:'Loyal',productId:'PROD-1745',productName:'Skin Repair Serum',brand:'VelvetTouch',productCategory:'Beauty',tags:['skincare','organic'],quantity:3,pricePerUnit:4970,discountPercentage:15,totalAmount:14910,finalAmount:12673.5,date:new Date('2022-05-04'),paymentMethod:'Cash',orderStatus:'Cancelled',deliveryType:'Standard',storeId:'ST-007',storeLocation:'Delhi',salespersonId:'EMP-4673',employeeName:'Khushi Agarwal'},
  {customerId:'CUST-39359',customerName:'Mahesh Yadav',phoneNumber:'9401182506',gender:'Female',age:41,customerRegion:'North',customerType:'New',productId:'PROD-5547',productName:'Gaming Mouse',brand:'TechPulse',productCategory:'Electronics',tags:['wireless','smart','accessories','portable'],quantity:5,pricePerUnit:1522,discountPercentage:24,totalAmount:7610,finalAmount:5783.6,date:new Date('2023-09-08'),paymentMethod:'Debit Card',orderStatus:'Completed',deliveryType:'Standard',storeId:'ST-015',storeLocation:'Kolkata',salespersonId:'EMP-2101',employeeName:'Yash Balyan'},
  {customerId:'CUST-96739',customerName:'Alisha Chopra',phoneNumber:'9664184287',gender:'Male',age:36,customerRegion:'South',customerType:'Loyal',productId:'PROD-5772',productName:'Smartwatch',brand:'CyberCore',productCategory:'Electronics',tags:['portable','accessories','wireless','smart'],quantity:4,pricePerUnit:3512,discountPercentage:21,totalAmount:14048,finalAmount:11097.92,date:new Date('2022-05-25'),paymentMethod:'Cash',orderStatus:'Pending',deliveryType:'Express',storeId:'ST-024',storeLocation:'Mumbai',salespersonId:'EMP-6690',employeeName:'Ashmi Jain'},
  {customerId:'CUST-20420',customerName:'Mahesh Yadav',phoneNumber:'9342595123',gender:'Female',age:63,customerRegion:'East',customerType:'Loyal',productId:'PROD-8625',productName:'Slim Fit Jeans',brand:'UrbanWeave',productCategory:'Clothing',tags:['casual','unisex','cotton','formal'],quantity:2,pricePerUnit:3970,discountPercentage:48,totalAmount:7940,finalAmount:4128.8,date:new Date('2022-07-19'),paymentMethod:'Cash',orderStatus:'Cancelled',deliveryType:'Standard',storeId:'ST-021',storeLocation:'Chennai',salespersonId:'EMP-2585',employeeName:'Ram Chaudhry'},
  {customerId:'CUST-50854',customerName:'Sneha Joshi',phoneNumber:'9236299364',gender:'Female',age:41,customerRegion:'West',customerType:'Returning',productId:'PROD-4665',productName:'Wireless Headphones',brand:'VoltEdge',productCategory:'Electronics',tags:['portable','gadgets','smart'],quantity:1,pricePerUnit:3258,discountPercentage:24,totalAmount:3258,finalAmount:2476.08,date:new Date('2021-10-13'),paymentMethod:'UPI',orderStatus:'Returned',deliveryType:'Store Pickup',storeId:'ST-035',storeLocation:'Pune',salespersonId:'EMP-1539',employeeName:'Khushi Agarwal'},
  {customerId:'CUST-24057',customerName:'Sneha Bansal',phoneNumber:'9800949235',gender:'Male',age:38,customerRegion:'Central',customerType:'Returning',productId:'PROD-1329',productName:'Formal Shirt',brand:'EliteWear',productCategory:'Clothing',tags:['cotton','formal'],quantity:4,pricePerUnit:3579,discountPercentage:33,totalAmount:14316,finalAmount:9591.72,date:new Date('2022-02-06'),paymentMethod:'Credit Card',orderStatus:'Returned',deliveryType:'Standard',storeId:'ST-043',storeLocation:'Lucknow',salespersonId:'EMP-1890',employeeName:'Yash Balyan'},
  {customerId:'CUST-47379',customerName:'Sanjay Das',phoneNumber:'9524489833',gender:'Female',age:36,customerRegion:'South',customerType:'Returning',productId:'PROD-7598',productName:'Smartwatch',brand:'CyberCore',productCategory:'Electronics',tags:['gadgets','accessories','portable'],quantity:1,pricePerUnit:4361,discountPercentage:46,totalAmount:4361,finalAmount:2354.94,date:new Date('2021-04-23'),paymentMethod:'Credit Card',orderStatus:'Returned',deliveryType:'Standard',storeId:'ST-039',storeLocation:'Mumbai',salespersonId:'EMP-9054',employeeName:'Ashmi Jain'},
  {customerId:'CUST-28339',customerName:'Alisha Iyer',phoneNumber:'9982354666',gender:'Male',age:43,customerRegion:'East',customerType:'New',productId:'PROD-6368',productName:'Hydrating Face Cream',brand:'GlowEssence',productCategory:'Beauty',tags:['makeup','fragrance-free','beauty','organic'],quantity:4,pricePerUnit:2665,discountPercentage:24,totalAmount:10660,finalAmount:8101.6,date:new Date('2021-09-23'),paymentMethod:'Debit Card',orderStatus:'Cancelled',deliveryType:'Standard',storeId:'ST-036',storeLocation:'Kolkata',salespersonId:'EMP-8350',employeeName:'Harsh Agarwal'},
  {customerId:'CUST-96946',customerName:'Nisha Singh',phoneNumber:'9711903829',gender:'Female',age:50,customerRegion:'Central',customerType:'Loyal',productId:'PROD-2810',productName:'Cotton T-Shirt',brand:'StreetLayer',productCategory:'Clothing',tags:['fashion','casual','cotton','formal'],quantity:4,pricePerUnit:391,discountPercentage:13,totalAmount:1564,finalAmount:1360.68,date:new Date('2022-07-23'),paymentMethod:'Cash',orderStatus:'Cancelled',deliveryType:'Express',storeId:'ST-010',storeLocation:'Bengaluru',salespersonId:'EMP-3561',employeeName:'Ashmi Jain'},
  {customerId:'CUST-14639',customerName:'Alisha Das',phoneNumber:'9138127587',gender:'Female',age:24,customerRegion:'South',customerType:'Returning',productId:'PROD-1058',productName:'Formal Shirt',brand:'StreetLayer',productCategory:'Clothing',tags:['casual','fashion','formal'],quantity:4,pricePerUnit:4295,discountPercentage:26,totalAmount:17180,finalAmount:12713.2,date:new Date('2021-03-09'),paymentMethod:'Wallet',orderStatus:'Cancelled',deliveryType:'Store Pickup',storeId:'ST-016',storeLocation:'Delhi',salespersonId:'EMP-2800',employeeName:'Khushi Agarwal'},
  {customerId:'CUST-51819',customerName:'Simran Das',phoneNumber:'9817084008',gender:'Female',age:29,customerRegion:'Central',customerType:'Returning',productId:'PROD-3673',productName:'Slim Fit Jeans',brand:'EliteWear',productCategory:'Clothing',tags:['casual','formal','fashion'],quantity:4,pricePerUnit:2382,discountPercentage:28,totalAmount:9528,finalAmount:6860.16,date:new Date('2021-03-08'),paymentMethod:'Cash',orderStatus:'Cancelled',deliveryType:'Store Pickup',storeId:'ST-031',storeLocation:'Kolkata',salespersonId:'EMP-4871',employeeName:'Ashmi Jain'},
  {customerId:'CUST-16498',customerName:'Kabir Khan',phoneNumber:'9343754282',gender:'Male',age:36,customerRegion:'Central',customerType:'Loyal',productId:'PROD-3658',productName:'Herbal Face Wash',brand:'GlowEssence',productCategory:'Beauty',tags:['makeup','organic'],quantity:3,pricePerUnit:1371,discountPercentage:42,totalAmount:4113,finalAmount:2385.54,date:new Date('2022-03-07'),paymentMethod:'Wallet',orderStatus:'Pending',deliveryType:'Standard',storeId:'ST-044',storeLocation:'Chennai',salespersonId:'EMP-3108',employeeName:'Kulasekhar Busi'},
  {customerId:'CUST-87689',customerName:'Neha Patel',phoneNumber:'9059422615',gender:'Female',age:32,customerRegion:'East',customerType:'Loyal',productId:'PROD-1216',productName:'Matte Lipstick',brand:'GlowEssence',productCategory:'Beauty',tags:['beauty','skincare'],quantity:4,pricePerUnit:1839,discountPercentage:37,totalAmount:7356,finalAmount:4634.28,date:new Date('2022-12-21'),paymentMethod:'Credit Card',orderStatus:'Pending',deliveryType:'Store Pickup',storeId:'ST-043',storeLocation:'Mumbai',salespersonId:'EMP-3228',employeeName:'Khushi Agarwal'}
];

mongoose.connect(process.env.MONGODB_URI).then(async()=>{
  await Sale.insertMany(newData);
  console.log(`Added ${newData.length} more records. Total now: ${await Sale.countDocuments()}`);
  process.exit(0);
}).catch(err=>{console.error(err);process.exit(1);});
