import 'dotenv/config';
import mongoose from 'mongoose';
import Sale from '../models/Sale.js';

const sampleData = [
  {
    customerId: "CUST-53321",
    customerName: "Suresh Iyer",
    phoneNumber: "9657125783",
    gender: "Female",
    age: 55,
    customerRegion: "North",
    customerType: "Returning",
    productId: "PROD-9434",
    productName: "Cotton T-Shirt",
    brand: "StreetLayer",
    productCategory: "Clothing",
    tags: ["unisex", "fashion", "cotton"],
    quantity: 4,
    pricePerUnit: 1103,
    discountPercentage: 12,
    totalAmount: 4412,
    finalAmount: 3882.56,
    date: new Date("2021-08-31"),
    paymentMethod: "UPI",
    orderStatus: "Pending",
    deliveryType: "Express",
    storeId: "ST-039",
    storeLocation: "Mumbai",
    salespersonId: "EMP-3759",
    employeeName: "Ashmi Jain"
  },
  {
    customerId: "CUST-76213",
    customerName: "Ritika Chopra",
    phoneNumber: "9100671247",
    gender: "Male",
    age: 42,
    customerRegion: "West",
    customerType: "New",
    productId: "PROD-2486",
    productName: "Bluetooth Speaker",
    brand: "VoltEdge",
    productCategory: "Electronics",
    tags: ["smart", "gadgets", "portable", "wireless"],
    quantity: 1,
    pricePerUnit: 4981,
    discountPercentage: 17,
    totalAmount: 4981,
    finalAmount: 4134.23,
    date: new Date("2021-04-28"),
    paymentMethod: "Credit Card",
    orderStatus: "Returned",
    deliveryType: "Store Pickup",
    storeId: "ST-006",
    storeLocation: "Jaipur",
    salespersonId: "EMP-6815",
    employeeName: "Khushi Agarwal"
  },
  {
    customerId: "CUST-10839",
    customerName: "Mahesh Mehta",
    phoneNumber: "9965297269",
    gender: "Male",
    age: 47,
    customerRegion: "East",
    customerType: "New",
    productId: "PROD-9154",
    productName: "Hooded Sweatshirt",
    brand: "ComfortLine",
    productCategory: "Clothing",
    tags: ["fashion", "casual", "unisex"],
    quantity: 1,
    pricePerUnit: 671,
    discountPercentage: 45,
    totalAmount: 671,
    finalAmount: 369.05,
    date: new Date("2021-07-12"),
    paymentMethod: "Credit Card",
    orderStatus: "Completed",
    deliveryType: "Store Pickup",
    storeId: "ST-016",
    storeLocation: "Kolkata",
    salespersonId: "EMP-6698",
    employeeName: "Ashmi Jain"
  },
  {
    customerId: "CUST-43872",
    customerName: "Suresh Sharma",
    phoneNumber: "9317845892",
    gender: "Male",
    age: 35,
    customerRegion: "South",
    customerType: "New",
    productId: "PROD-7475",
    productName: "Bluetooth Speaker",
    brand: "CyberCore",
    productCategory: "Electronics",
    tags: ["smart", "portable", "wireless"],
    quantity: 3,
    pricePerUnit: 2720,
    discountPercentage: 45,
    totalAmount: 8160,
    finalAmount: 4488.0,
    date: new Date("2023-06-16"),
    paymentMethod: "Cash",
    orderStatus: "Returned",
    deliveryType: "Express",
    storeId: "ST-032",
    storeLocation: "Jaipur",
    salespersonId: "EMP-7244",
    employeeName: "Deepak Goyal"
  },
  {
    customerId: "CUST-66880",
    customerName: "Ritika Joshi",
    phoneNumber: "9642689633",
    gender: "Female",
    age: 47,
    customerRegion: "North",
    customerType: "Loyal",
    productId: "PROD-2390",
    productName: "Casual Kurta",
    brand: "StreetLayer",
    productCategory: "Clothing",
    tags: ["casual", "fashion"],
    quantity: 5,
    pricePerUnit: 1787,
    discountPercentage: 30,
    totalAmount: 8935,
    finalAmount: 6254.5,
    date: new Date("2022-07-17"),
    paymentMethod: "Cash",
    orderStatus: "Returned",
    deliveryType: "Express",
    storeId: "ST-035",
    storeLocation: "Mumbai",
    salespersonId: "EMP-6938",
    employeeName: "Yash Balyan"
  },
  {
    customerId: "CUST-64912",
    customerName: "Sanjay Bansal",
    phoneNumber: "9268904111",
    gender: "Female",
    age: 57,
    customerRegion: "West",
    customerType: "New",
    productId: "PROD-7692",
    productName: "Matte Lipstick",
    brand: "VelvetTouch",
    productCategory: "Beauty",
    tags: ["organic", "skincare"],
    quantity: 1,
    pricePerUnit: 4707,
    discountPercentage: 2,
    totalAmount: 4707,
    finalAmount: 4612.86,
    date: new Date("2023-03-18"),
    paymentMethod: "Credit Card",
    orderStatus: "Cancelled",
    deliveryType: "Store Pickup",
    storeId: "ST-002",
    storeLocation: "Jaipur",
    salespersonId: "EMP-5075",
    employeeName: "Ram Chaudhry"
  },
  {
    customerId: "CUST-58160",
    customerName: "Mahesh Mehta",
    phoneNumber: "9266063747",
    gender: "Female",
    age: 53,
    customerRegion: "West",
    customerType: "New",
    productId: "PROD-3174",
    productName: "Wireless Headphones",
    brand: "NovaGear",
    productCategory: "Electronics",
    tags: ["smart", "portable", "accessories"],
    quantity: 3,
    pricePerUnit: 2749,
    discountPercentage: 21,
    totalAmount: 8247,
    finalAmount: 6515.13,
    date: new Date("2022-06-10"),
    paymentMethod: "Wallet",
    orderStatus: "Completed",
    deliveryType: "Express",
    storeId: "ST-008",
    storeLocation: "Bengaluru",
    salespersonId: "EMP-4049",
    employeeName: "Ram Chaudhry"
  },
  {
    customerId: "CUST-26938",
    customerName: "Farhan Khan",
    phoneNumber: "9491736503",
    gender: "Male",
    age: 40,
    customerRegion: "Central",
    customerType: "Loyal",
    productId: "PROD-8823",
    productName: "Bluetooth Speaker",
    brand: "TechPulse",
    productCategory: "Electronics",
    tags: ["portable", "gadgets", "accessories"],
    quantity: 5,
    pricePerUnit: 1223,
    discountPercentage: 9,
    totalAmount: 6115,
    finalAmount: 5564.65,
    date: new Date("2023-09-17"),
    paymentMethod: "Wallet",
    orderStatus: "Completed",
    deliveryType: "Standard",
    storeId: "ST-042",
    storeLocation: "Bengaluru",
    salespersonId: "EMP-7771",
    employeeName: "Yash Balyan"
  },
  {
    customerId: "CUST-23645",
    customerName: "Prerna Chopra",
    phoneNumber: "9387515030",
    gender: "Male",
    age: 24,
    customerRegion: "West",
    customerType: "New",
    productId: "PROD-6571",
    productName: "Bluetooth Speaker",
    brand: "VoltEdge",
    productCategory: "Electronics",
    tags: ["accessories", "wireless"],
    quantity: 1,
    pricePerUnit: 2601,
    discountPercentage: 13,
    totalAmount: 2601,
    finalAmount: 2262.87,
    date: new Date("2021-07-18"),
    paymentMethod: "UPI",
    orderStatus: "Pending",
    deliveryType: "Store Pickup",
    storeId: "ST-024",
    storeLocation: "Bengaluru",
    salespersonId: "EMP-9226",
    employeeName: "Harsh Agarwal"
  },
  {
    customerId: "CUST-56533",
    customerName: "Anjali Agarwal",
    phoneNumber: "9069392523",
    gender: "Female",
    age: 54,
    customerRegion: "West",
    customerType: "Loyal",
    productId: "PROD-7533",
    productName: "Bluetooth Speaker",
    brand: "VoltEdge",
    productCategory: "Electronics",
    tags: ["gadgets", "accessories"],
    quantity: 5,
    pricePerUnit: 4779,
    discountPercentage: 48,
    totalAmount: 23895,
    finalAmount: 12425.4,
    date: new Date("2023-01-15"),
    paymentMethod: "Credit Card",
    orderStatus: "Pending",
    deliveryType: "Store Pickup",
    storeId: "ST-038",
    storeLocation: "Ahmedabad",
    salespersonId: "EMP-5387",
    employeeName: "Khushi Agarwal"
  }
];

async function seedDatabase() {
  try {
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/retail_sales';
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    await Sale.deleteMany({});
    console.log('Cleared existing data');

    await Sale.insertMany(sampleData);
    console.log(`Inserted ${sampleData.length} records successfully`);

    await mongoose.connection.close();
    console.log('Done!');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

seedDatabase();
